/**
 * Global IST Timezone Utilities for EduQuizX
 * 
 * Official exam timezone: Asia/Kolkata (Indian Standard Time, UTC+05:30)
 * All exam-facing displays, deadlines, schedules, and inputs MUST be in IST.
 * Internal data transmission and storage remain strict UTC instants.
 */

export const APP_TIMEZONE = "Asia/Kolkata";

/**
 * Safely parses any date or ISO string into a JavaScript Date object.
 * If the string contains an ISO date-time ('T') but lacks an explicit timezone indicator ('Z', '+', '-'),
 * it explicitly interprets it as UTC (preserving legacy DB records generated by datetime.utcnow()).
 */
export function parseUtcDate(val: string | Date | null | undefined): Date | null {
  if (!val) return null;
  if (val instanceof Date) {
    return isNaN(val.getTime()) ? null : val;
  }
  let str = String(val).trim();
  if (!str) return null;

  // If string has ISO date-time 'T' but no timezone offset (neither Z nor +/-offset),
  // assume UTC by appending 'Z'
  if (str.includes("T") && !str.endsWith("Z") && !/[+-]\d{2}(:\d{2})?$/.test(str)) {
    str = str + "Z";
  }

  const d = new Date(str);
  return isNaN(d.getTime()) ? null : d;
}

/**
 * Formats a date in Asia/Kolkata (IST) for display.
 */
export function formatIST(
  val: string | Date | null | undefined,
  options?: Intl.DateTimeFormatOptions
): string {
  const d = parseUtcDate(val);
  if (!d) return "—";
  const defaultOpts: Intl.DateTimeFormatOptions = {
    timeZone: APP_TIMEZONE,
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
    ...options,
  };
  return new Intl.DateTimeFormat("en-US", defaultOpts).format(d);
}

/**
 * Formats date only in IST, e.g. "10 Sep 2026".
 */
export function formatISTDate(val: string | Date | null | undefined): string {
  const d = parseUtcDate(val);
  if (!d) return "—";
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: APP_TIMEZONE,
    day: "numeric",
    month: "short",
    year: "numeric"
  }).formatToParts(d);
  const day = parts.find(p => p.type === "day")?.value || "";
  const month = parts.find(p => p.type === "month")?.value || "";
  const year = parts.find(p => p.type === "year")?.value || "";
  return `${day} ${month} ${year}`.trim();
}

/**
 * Formats time only in IST, e.g. "10:00 AM IST".
 */
export function formatISTTime(val: string | Date | null | undefined): string {
  const d = parseUtcDate(val);
  if (!d) return "—";
  const time = new Intl.DateTimeFormat("en-US", {
    timeZone: APP_TIMEZONE,
    hour: "2-digit",
    minute: "2-digit",
    hour12: true
  }).format(d);
  return `${time} IST`;
}

/**
 * Formats full datetime in IST, e.g. "10 Sep 2026, 10:00 AM IST".
 */
export function formatISTDateTime(val: string | Date | null | undefined): string {
  const d = parseUtcDate(val);
  if (!d) return "—";
  return `${formatISTDate(d)}, ${formatISTTime(d)}`;
}

/**
 * Formats an exam schedule range in IST, e.g. "10 Sep 2026, 10:00 AM – 12:00 PM IST".
 */
export function formatExamScheduleRange(
  startVal: string | Date | null | undefined,
  endVal: string | Date | null | undefined
): string {
  const start = parseUtcDate(startVal);
  const end = parseUtcDate(endVal);

  if (!start && !end) return "Continuous Open";
  if (!start && end) return `Closes ${formatISTDateTime(end)}`;
  if (start && !end) return `Opens ${formatISTDateTime(start)}`;

  const startDateStr = formatISTDate(start);
  const endDateStr = formatISTDate(end);
  const startTimeStr = formatISTTime(start);
  const endTimeStr = formatISTTime(end);

  if (startDateStr === endDateStr) {
    // Same day
    const startTimeOnly = startTimeStr.replace(" IST", "");
    return `${startDateStr}, ${startTimeOnly} – ${endTimeStr}`;
  }
  return `${formatISTDateTime(start)} – ${formatISTDateTime(end)}`;
}

/**
 * Formats a Date object or UTC string into 'YYYY-MM-DDTHH:mm' in Asia/Kolkata
 * for <input type="datetime-local"> on the teacher exam scheduling form.
 */
export function formatISTForInput(val: string | Date | null | undefined): string {
  const d = parseUtcDate(val);
  if (!d) return "";
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: APP_TIMEZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23"
  }).formatToParts(d);
  const getPart = (type: string) => parts.find(p => p.type === type)?.value || "00";
  return `${getPart("year")}-${getPart("month")}-${getPart("day")}T${getPart("hour")}:${getPart("minute")}`;
}

/**
 * Converts a teacher's IST scheduling input ('YYYY-MM-DDTHH:mm') into an absolute UTC ISO string.
 * Input: "2026-09-10T10:00"
 * Output: "2026-09-10T04:30:00.000Z"
 * 
 * Safety:
 * - Interprets datetime-local inputs strictly as IST (+05:30).
 * - Never depends on the client browser's local timezone.
 */
export function parseISTInputToUtcIso(inputStr: string | null | undefined): string | null {
  if (!inputStr) return null;
  const s = String(inputStr).trim();
  if (!s) return null;

  // Match YYYY-MM-DDTHH:mm or YYYY-MM-DDTHH:mm:ss
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$/.test(s)) {
    const hasSeconds = s.split("T")[1].split(":").length === 3;
    const isoWithISTOffset = hasSeconds ? `${s}+05:30` : `${s}:00+05:30`;
    const d = new Date(isoWithISTOffset);
    return isNaN(d.getTime()) ? null : d.toISOString();
  }

  // If already an ISO string with Z or offset, parse directly
  const d = parseUtcDate(s);
  return d ? d.toISOString() : null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Backward Compatibility Aliases (all backed by the centralized IST engine)
// ─────────────────────────────────────────────────────────────────────────────
export const formatLocalizedDate = formatIST;
export const formatLocalizedTime = formatISTTime;
export const formatLocalDateTime = formatISTForInput;
export const formatLocalForInput = formatISTForInput;
